/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./public/**/*.{html,js}"],
  theme: {
    extend: {
      "colors": {
        "tertiary-container": "#ff8c38",
        "surface-tint": "#ff6b00",
        "on-background": "rgb(var(--color-on-surface) / <alpha-value>)",
        "tertiary-fixed": "#ffcca8",
        "on-tertiary": "#2b1000",
        "surface-bright": "rgb(var(--color-surface-bright) / <alpha-value>)",
        "secondary-container": "rgb(var(--color-secondary-container) / <alpha-value>)",
        "surface": "rgb(var(--color-surface) / <alpha-value>)",
        "error-container": "#93000a",
        "primary-fixed-dim": "#ff6b00",
        "on-tertiary-fixed": "#2b1000",
        "on-secondary-fixed-variant": "#634735",
        "tertiary": "#fff0e6",
        "on-secondary-container": "rgb(var(--color-on-secondary-container) / <alpha-value>)",
        "on-primary-container": "#ff6b00",
        "secondary-fixed-dim": "#e0c2b0",
        "on-error-container": "#ffdad6",
        "surface-dim": "rgb(var(--color-surface-dim) / <alpha-value>)",
        "outline-variant": "#593c28",
        "inverse-surface": "rgb(var(--color-inverse-surface) / <alpha-value>)",
        "on-secondary": "#2b1000",
        "surface-container": "rgb(var(--color-surface-container) / <alpha-value>)",
        "surface-container-low": "rgb(var(--color-surface-container-low) / <alpha-value>)",
        "secondary": "rgb(var(--color-secondary) / <alpha-value>)",
        "on-error": "#690005",
        "surface-container-highest": "rgb(var(--color-surface-container-highest) / <alpha-value>)",
        "surface-variant": "rgb(var(--color-surface-container-highest) / <alpha-value>)",
        "error": "#ffb4ab",
        "on-secondary-fixed": "#1b0a00",
        "inverse-on-surface": "rgb(var(--color-inverse-on-surface) / <alpha-value>)",
        "background": "rgb(var(--color-surface) / <alpha-value>)",
        "on-surface-variant": "rgb(var(--color-on-surface-variant) / <alpha-value>)",
        "inverse-primary": "#ff6b00",
        "primary": "#ff6b00",
        "on-surface": "rgb(var(--color-on-surface) / <alpha-value>)",
        "on-primary-fixed": "#1b0a00",
        "tertiary-fixed-dim": "#ff9e54",
        "primary-container": "#ff6b00",
        "surface-container-high": "rgb(var(--color-surface-container-high) / <alpha-value>)",
        "primary-fixed": "#ffaa66",
        "on-primary-fixed-variant": "#471c00",
        "surface-container-lowest": "rgb(var(--color-surface-dim) / <alpha-value>)",
        "on-tertiary-container": "#7a3100",
        "outline": "#ff9e54",
        "on-tertiary-fixed-variant": "#592400",
        "on-primary": "#ffffff",
        "secondary-fixed": "#ffe4d4"
      },
      "borderRadius": {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
      "spacing": {
        "gutter": "24px",
        "container-max": "1440px",
        "unit": "8px",
        "margin-mobile": "16px",
        "margin-desktop": "48px",
        "section-gap": "72px"
      },
      "fontFamily": {
        "label-caps": ["DM Sans"],
        "display-lg-mobile": ["DM Sans"],
        "headline-xl": ["DM Sans"],
        "body-lg": ["Lexend"],
        "display-lg": ["DM Sans"],
        "body-md": ["Lexend"],
        "headline-md": ["DM Sans"]
      },
      "fontSize": {
        "label-caps": ["12px", { "lineHeight": "1", "letterSpacing": "0.15em", "fontWeight": "600" }],
        "display-lg-mobile": ["36px", { "lineHeight": "1.15", "letterSpacing": "-0.02em", "fontWeight": "700" }],
        "headline-xl": ["32px", { "lineHeight": "1.2", "letterSpacing": "-0.02em", "fontWeight": "600" }],
        "body-lg": ["16px", { "lineHeight": "1.6", "letterSpacing": "0.01em", "fontWeight": "300" }],
        "display-lg": ["72px", { "lineHeight": "1.08", "letterSpacing": "-0.03em", "fontWeight": "700" }],
        "body-md": ["15px", { "lineHeight": "1.6", "fontWeight": "300" }],
        "headline-md": ["24px", { "lineHeight": "1.3", "fontWeight": "500" }]
      }
    },
  },
  plugins: [],
}
