/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./public/**/*.{html,js}"],
  theme: {
    extend: {
      "colors": {
        "tertiary-container": "#ded0c9",
        "surface-tint": "#e9c24d",
        "on-background": "#e8e1de",
        "tertiary-fixed": "#eee0d9",
        "on-tertiary": "#372f2a",
        "surface-bright": "#3c3836",
        "secondary-container": "#494a41",
        "surface": "#151311",
        "error-container": "#93000a",
        "primary-fixed-dim": "#e9c24d",
        "on-tertiary-fixed": "#211a16",
        "on-secondary-fixed-variant": "#46473f",
        "tertiary": "#fbece5",
        "on-secondary-container": "#b9b9ae",
        "on-primary-container": "#705800",
        "secondary-fixed-dim": "#c7c7bc",
        "on-error-container": "#ffdad6",
        "surface-dim": "#151311",
        "outline-variant": "#4d4635",
        "inverse-surface": "#e8e1de",
        "on-secondary": "#303129",
        "surface-container": "#221f1d",
        "surface-container-low": "#1e1b19",
        "secondary": "#c7c7bc",
        "on-error": "#690005",
        "surface-container-highest": "#373432",
        "surface-variant": "#373432",
        "error": "#ffb4ab",
        "on-secondary-fixed": "#1b1c15",
        "inverse-on-surface": "#33302e",
        "background": "#151311",
        "on-surface-variant": "#d0c5b0",
        "inverse-primary": "#745b00",
        "primary": "#ffeec7",
        "on-surface": "#e8e1de",
        "on-primary-fixed": "#241a00",
        "tertiary-fixed-dim": "#d1c4bd",
        "primary-container": "#f7cf58",
        "surface-container-high": "#2c2927",
        "primary-fixed": "#ffe08b",
        "on-primary-fixed-variant": "#584400",
        "surface-container-lowest": "#100e0c",
        "on-tertiary-container": "#625953",
        "outline": "#99907c",
        "on-tertiary-fixed-variant": "#4e4540",
        "on-primary": "#3d2f00",
        "secondary-fixed": "#e4e3d7"
      },
      "spacing": {
        "gutter": "32px",
        "container-max": "1440px",
        "unit": "8px",
        "margin-mobile": "24px",
        "margin-desktop": "80px",
        "section-gap": "160px"
      },
      "fontFamily": {
        "label-caps": ["DM Sans"],
        "display-lg-mobile": ["DM Sans"],
        "headline-xl": ["DM Sans"],
        "body-lg": ["Lexend"],
        "display-lg": ["DM Sans"],
        "body-md": ["Lexend"],
        "headline-md": ["DM Sans"]
      },
    },
  },
  plugins: [],
}
